//! Compatibility import surface for managed-storage layout names.
//!
//! The definitions and their frozen manifest are owned by
//! `tine_storage::formats`; this module contains no path values.

pub use tine_storage::formats::{
    ARCHIVE_BATCHES_DIR, ARCHIVE_BOOTSTRAP_DIR, ARCHIVE_INSTANCE_CLAIM_FILE,
    ARCHIVE_LAZY_GENESIS_DIR, ARCHIVE_OBJECTS_DIR, BLOCK_CLAIM_INDEX_DIR, BLOCK_CLAIM_INDEX_FILE,
    BOOTSTRAP_AGGREGATES_DIR, BOOTSTRAP_COMMITS_DIR, BOOTSTRAP_EVIDENCE_DIR, BOOTSTRAP_OBJECTS_DIR,
    BOOTSTRAP_PARTS_DIR, BOOTSTRAP_PART_PACKS_DIR, BOOTSTRAP_PART_SPANS_DIR,
    BOOTSTRAP_SOURCE_BLOB_DIR, BOOTSTRAP_SOURCE_CAPTURE_CHUNKS_DIR, BOOTSTRAP_SOURCE_CAPTURE_DIR,
    BOOTSTRAP_SOURCE_CAPTURE_MANIFEST_FILE, BOOTSTRAP_SOURCE_CHUNKS_DIR,
    BOOTSTRAP_SOURCE_CHUNKS_FILE, BOOTSTRAP_SOURCE_ENTRIES_FILE, BOOTSTRAP_SOURCE_INVENTORY_DIR,
    BOOTSTRAP_SOURCE_INVENTORY_FILE, BOOTSTRAP_STREAM_AGGREGATE_FILE,
    BOOTSTRAP_STREAM_BLOB_PAGES_DIR, BOOTSTRAP_STREAM_BOUNDARY_SPOOL_FILE,
    BOOTSTRAP_STREAM_COMMIT_FILE, BOOTSTRAP_STREAM_DIR, BOOTSTRAP_STREAM_INVENTORY_PAGES_DIR,
    BOOTSTRAP_STREAM_OPERATION_SPOOL_FILE, BOOTSTRAP_STREAM_PARTS_DIR,
    BOOTSTRAP_STREAM_PART_EVIDENCE_FILE, BOOTSTRAP_STREAM_PART_MANIFEST_FILE,
    BOOTSTRAP_STREAM_PART_OBJECTS_FILE, BOOTSTRAP_STREAM_PART_SPANS_FILE,
    BOOTSTRAP_STREAM_SEAL_FILE, COMMIT_MARKER_FILE, COMMIT_MARKER_STAGE_FILE,
    ENGINE_HISTORY_CLAIM_FILE, ENGINE_HISTORY_DIR, ENGINE_HISTORY_HEAD_FILE,
    ENGINE_HISTORY_NODES_DIR, ENGINE_HISTORY_ROOTS_DIR, ENGINE_HISTORY_ROOT_SUFFIX,
    ENGINE_HISTORY_TRANSITION_LOCK_FILE, ENROLLMENT_AUTHORITY_FILE,
    ENROLLMENT_AUTHORITY_TEMP_PREFIX, ENROLLMENT_DIR, ENROLLMENT_HEAD_FILE,
    ENROLLMENT_HEAD_TEMP_PREFIX, ENROLLMENT_LEASE_FILE, ENROLLMENT_LOCAL_DIR,
    ENROLLMENT_RECORDS_DIR, ENROLLMENT_RECORD_SUFFIX, ENROLLMENT_RECORD_TEMP_PREFIX,
    ENROLLMENT_STORAGE_DIR, ENROLLMENT_VERSION_DIR, INTENT_NAMESPACE_AUTHORITY_SUFFIX,
    INTENT_NAMESPACE_RESERVATION_SUFFIX, LAZY_GENESIS_CATALOG_FILE, LAZY_GENESIS_COMMIT_FILE,
    LAZY_GENESIS_MANIFEST_FILE, LAZY_GENESIS_SEGMENT_PREFIX, LAZY_GENESIS_SEGMENT_SUFFIX,
    LINEAGE_CLAIM_FILE, LOCAL_ACTIVATION_RESERVATION_FILE, LOCAL_AUTHORSHIP_RECEIPT_DIR,
    LOGSEQ_CLAIM_INDEX_DIR, MANAGED_LOCAL_JOURNAL_DIR, MANIFEST_FILE, MIGRATION_BACKUP_ROOT_DIR,
    MIGRATION_PAYLOAD_DIR, MUTATION_AUTHORITY_LEASE_SUFFIX, MUTATION_AUTHORITY_SUFFIX,
    PAGE_NAME_EXACT_BLOB_SUFFIX, PAGE_NAME_EXACT_NAMES_DIR, PAGE_NAME_NODES_DIR,
    PAGE_NAME_OWNERSHIP_INDEX_DIR, PAGE_NAME_STORE_CLAIM_FILE, PORTABLE_PATH_INDEX_DIR,
    PRIVATE_BINDING_DIR, PRIVATE_BINDING_FILE, PRIVATE_RECOVERY_DIR, PROJECTION_ATTEMPTS_DIR,
    PROJECTION_BASES_DIR, PROJECTION_CLEANUP_ROUND_0_DIR, PROJECTION_CLEANUP_ROUND_1_DIR,
    PROJECTION_CLEANUP_ROUND_STATE_FILE, PROJECTION_COMPLETIONS_DIR, PROJECTION_FORENSICS_DIR,
    PROJECTION_INTENTS_DIR, PROJECTION_PENDING_CLEANUP_AUTHORITY_FILE,
    PROJECTION_PENDING_CLEANUP_DIR, PROJECTION_PENDING_CLEANUP_SUFFIX, PROJECTION_STORE_CLAIM_FILE,
    PROJECTION_STORE_INIT_FILE, PROJECTION_WORK_CLAIM_FILE, PROJECTION_WORK_DIR,
    PROJECTION_WORK_HEAD_FILE, PROJECTION_WORK_NODE_SUFFIX, PROJECTION_WORK_PREPARED_SUFFIX,
    PROJECTION_WORK_ROOT_SUFFIX, PROMOTED_RUNTIME_STATE_FILE, PROOF_FILE, PROOF_STAGE_FILE,
    PROVIDER_DEVICE_AUTHORITY_FILE, PROVIDER_INBOX_DIR, PROVIDER_OUTBOX_DIR,
    PROVIDER_PENDING_PUBLICATION_DIR, RECONCILIATION_DATABASE_FILE,
    RECONCILIATION_DATABASE_JOURNAL_FILE, RECONCILIATION_DATABASE_SHM_FILE,
    RECONCILIATION_DATABASE_WAL_FILE, RECONCILIATION_DIR, RECONCILIATION_FORENSIC_DATABASE_FILE,
    RECONCILIATION_FORENSIC_EVIDENCE_COMPLETE, RECONCILIATION_FORENSIC_JOURNAL_FILE,
    RECONCILIATION_FORENSIC_PREFIX, RECONCILIATION_FORENSIC_REBUILD_COMPLETE,
    RECONCILIATION_FORENSIC_SHM_FILE, RECONCILIATION_FORENSIC_WAL_FILE, REFERENCE_CATALOG_DIR,
    RESTORE_PROOF_FILE, RESTORE_PROOF_STAGE_FILE, RESUME_POINT_DIR, RESUME_POINT_SUFFIX,
    RESUME_POINT_TEMP_PREFIX, SHADOW_ROOT_DIR, SHARED_ENROLLMENT_DESCRIPTOR_PATH,
    SHARED_ENROLLMENT_DIR, SHARED_FRONTIER_HEADS_DIR, SHARED_MANIFESTS_DIR,
    SHARED_MANIFEST_RECOVERY_BLOBS_DIR, SHARED_MANIFEST_RECOVERY_LINKS_DIR, SHARED_OBJECTS_DIR,
    SHARED_PUBLICATION_INTENTS_DIR, SHARED_REMOVED_DIR, SHARED_RENAME_EVIDENCE_DIR,
    SHARED_TEMP_DIR, SQLITE_APPLIER_LOCK_FILE, SQLITE_RUNTIME_DIR, SQLITE_WORKSPACES_DIR,
};

#[cfg(test)]
mod tests {
    #[test]
    fn compatibility_surface_has_no_layout_definitions_and_reexports_every_storage_atom() {
        const SOURCE: &str = include_str!("sync_layout.rs");
        let production = SOURCE
            .split("#[cfg(test)]")
            .next()
            .expect("compatibility surface has a production region");
        assert!(
            !production.contains("pub const"),
            "Tine core must not regain a second managed-layout source of truth"
        );
        for row in tine_storage::formats::FORMAT_MANIFEST
            .iter()
            .filter(|row| row.artifact == "managed storage layout")
        {
            assert!(
                production.contains(row.name),
                "storage-owned layout atom {} is missing from the core compatibility surface",
                row.name
            );
        }
    }
}
