import { afterEach, expect, it, vi } from "vitest";
import { backend } from "../../backend";
import { runComparison } from "./orchestrator";
const mocks = vi.hoisted(() => ({ warm: vi.fn(), fresh: vi.fn(), dispose: vi.fn() }));
vi.mock("./mldoc-client", () => ({ MldocClient: class { parseWarm = mocks.warm; parseFresh = mocks.fresh; dispose = mocks.dispose; } }));
vi.mock("./lsdoc-document", () => ({ lsdocDocumentAvailable: () => true, lsdocVersion: () => "test", parseLsdocDocument: () => ({ blocks: [], refs: { page: [], block: [] } }) }));
afterEach(() => { vi.restoreAllMocks(); vi.clearAllMocks(); });
it.each(["diff", "bench", "both"] as const)("L13:84: retired %s work releases the client and starts no more parses", async (mode) => {
  vi.spyOn(backend(), "graphSourceFiles").mockResolvedValue({ files: Array.from({ length: 3 }, (_, i) => ({ rel: `pages/P${i}.md`, bytes: 4, format: "md" as const, text: "- x\n" })), skipped: [] });
  let live = true, finish!: (value: unknown) => void;
  mocks.warm.mockImplementationOnce(() => new Promise((r) => { finish = r; })).mockResolvedValue({ ok: true, projection: { blocks: [], refs: { page: [], block: [] } } });
  const progress = vi.fn();
  const running = runComparison({ mode, includeJournals: false, fast: false, timeoutMs: 100 }, progress, () => live);
  await vi.waitFor(() => expect(mocks.warm).toHaveBeenCalledTimes(1));
  live = false;
  const count = progress.mock.calls.length;
  finish({ ok: true, projection: { blocks: [], refs: { page: [], block: [] } } });
  expect(await running).toEqual({ kind: "stale" });
  expect(mocks.warm).toHaveBeenCalledTimes(1);
  expect(mocks.fresh).not.toHaveBeenCalled();
  expect(progress).toHaveBeenCalledTimes(count);
  expect(mocks.dispose).toHaveBeenCalledTimes(1);
});
