#!/usr/bin/env node
// Regenerate the vendored frontend parser (src/render/wasm/) from crates/lsdoc-wasm.
//
// Run via `npm run build:wasm`. Needs `wasm-pack` + the `wasm32-unknown-unknown`
// target (NOT needed to merely build/run Tine — only to regenerate after an lsdoc
// bump). See docs/wasm-parse-plan.md.
//
// Steps:
//   1. Read the lsdoc git tag from crates/tine-core/Cargo.toml (the single source
//      of truth) and from crates/lsdoc-wasm/Cargo.toml; REFUSE if they differ
//      (the stale-wasm / forgot-to-bump guard, plan §7D).
//   2. Refuse native/standalone shared-search lock drift, then wasm-pack build
//      --target web (release), with LSDOC_TAG stamped in.
//   3. Fingerprint the resolved search dependency closure plus its local leaf
//      and wrapper sources, then stamp it beside the base64-encoded .wasm in
//      src/render/wasm/lsdoc_wasm_bytes.ts. Copy the wasm-bindgen JS glue + .d.ts.
//      These committed files are what the app and CI consume — no fetch, no wasm
//      toolchain at app-build time.
//
// This generator intentionally does not update scripts/wasm-size-ceiling.json:
// that ceiling is an independently reviewed measurement, not generated output.

import { execFileSync } from "node:child_process";
import { readFileSync, writeFileSync, mkdtempSync, mkdirSync, existsSync } from "node:fs";
import { tmpdir } from "node:os";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { searchLockAlignmentProblems, searchSourceFingerprint } from "./wasm-search-guard-lib.mjs";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const outDir = join(root, "src", "render", "wasm");

function lsdocTag(cargoTomlRelPath) {
  const txt = readFileSync(join(root, cargoTomlRelPath), "utf8");
  const m = txt.match(/lsdoc\s*=\s*\{[^}]*\btag\s*=\s*"([^"]+)"/);
  if (!m) throw new Error(`could not find lsdoc tag in ${cargoTomlRelPath}`);
  return m[1];
}

const coreTag = lsdocTag("crates/tine-core/Cargo.toml");
const wrapTag = lsdocTag("crates/lsdoc-wasm/Cargo.toml");
if (coreTag !== wrapTag) {
  console.error(
    `\n  lsdoc pin mismatch (plan §7D guard):\n` +
      `    crates/tine-core/Cargo.toml  -> ${coreTag}\n` +
      `    crates/lsdoc-wasm/Cargo.toml -> ${wrapTag}\n` +
      `  Bump both to the same tag before regenerating the wasm.\n`,
  );
  process.exit(1);
}
console.log(`lsdoc pin: ${coreTag} (tine-core == lsdoc-wasm ✓)`);

function requireSearchLockAlignment() {
  const problems = searchLockAlignmentProblems(root);
  if (problems.length) {
    console.error(
      `\n  Native/Wasm shared-search dependency mismatch (build aborted):\n` +
        problems.map((problem) => `    - ${problem}\n`).join("") +
        `  Align crates/lsdoc-wasm/Cargo.lock with Cargo.lock before regenerating the Wasm.\n`,
    );
    process.exit(1);
  }
}

// A first build has no standalone lock to compare yet. Once present, reject a
// known split before paying for wasm-pack; verify again afterward in case Cargo
// resolved a new version during this build.
if (existsSync(join(root, "crates", "lsdoc-wasm", "Cargo.lock"))) {
  requireSearchLockAlignment();
}

const tmp = mkdtempSync(join(tmpdir(), "lsdoc-wasm-"));
console.log(`wasm-pack build → ${tmp}`);
// Panic locations embed source paths. Without the remap the checkout's
// absolute path (a private worktree name) ships in the public bytes, and the
// measured size ceiling moves with the length of that name.
const rustflags = [process.env.RUSTFLAGS, `--remap-path-prefix=${root}=/tine`].filter(Boolean).join(" ");
execFileSync(
  "wasm-pack",
  ["build", "crates/lsdoc-wasm", "--target", "web", "--release", "--out-dir", tmp, "--out-name", "lsdoc_wasm"],
  { cwd: root, stdio: "inherit", env: { ...process.env, LSDOC_TAG: coreTag, RUSTFLAGS: rustflags } },
);

requireSearchLockAlignment();
const searchSourceSha256 = searchSourceFingerprint(root);

mkdirSync(outDir, { recursive: true });

// 1) Base64-inline the wasm bytes (no fetch under Tauri custom-protocol).
const wasm = readFileSync(join(tmp, "lsdoc_wasm_bg.wasm"));
const b64 = wasm.toString("base64");
const bytesTs =
  `// GENERATED by scripts/build-wasm.mjs — DO NOT EDIT.\n` +
  `// lsdoc ${coreTag}; raw wasm ${wasm.length} bytes, base64 ${b64.length} chars.\n` +
  `// Base64-inlined so the parser loads with NO fetch (works under Tauri's custom\n` +
  `// protocol + offline). Regenerate via \`npm run build:wasm\`.\n` +
  `export const LSDOC_TAG = ${JSON.stringify(coreTag)};\n` +
  `export const SEARCH_SOURCE_SHA256 = ${JSON.stringify(searchSourceSha256)};\n` +
  `export const WASM_B64 = ${JSON.stringify(b64)};\n`;
writeFileSync(join(outDir, "lsdoc_wasm_bytes.ts"), bytesTs);

// 2) Vendor the wasm-bindgen JS glue + its type defs. Neutralize the glue's
//    default-path branch: `new URL('lsdoc_wasm_bg.wasm', import.meta.url)` would
//    make Vite statically emit/resolve the raw .wasm at build time — but we vendor
//    base64 only (no raw .wasm) and ALWAYS pass bytes to init(), so that branch is
//    dead code. Replace it so Vite never sees the asset URL.
let glue = readFileSync(join(tmp, "lsdoc_wasm.js"), "utf8");
const defaultPath = "module_or_path = new URL('lsdoc_wasm_bg.wasm', import.meta.url);";
if (!glue.includes(defaultPath)) {
  throw new Error(
    "build-wasm: expected default-path line not found in glue — wasm-bindgen output " +
      "changed; re-check the Vite asset-URL neutralization in scripts/build-wasm.mjs.",
  );
}
glue = glue.replace(
  defaultPath,
  "throw new Error('lsdoc-wasm: init() must be called with explicit bytes (see src/render/parse.ts); default fetch path is disabled.');",
);
const reinitAnchor = "export { initSync, __wbg_init as default };\n";
if (!glue.includes(reinitAnchor)) {
  throw new Error(
    "build-wasm: expected final export line not found in glue — wasm-bindgen output " +
      "changed; re-check the Tine crash-recovery reinit injection in scripts/build-wasm.mjs.",
  );
}
if (glue.includes("__tineReinstantiate")) {
  throw new Error("build-wasm: __tineReinstantiate already present in generated glue; refuse to duplicate it.");
}
glue = glue.replace(
  reinitAnchor,
  reinitAnchor +
    `
// Tine crash-recovery: rebuild a FRESH wasm instance from the retained compiled module,
// bypassing the init()/initSync() \`wasm !== undefined\` early-return. Used by
// src/render/parse.ts to recover from a parser trap (poisoned instance). Same-module
// scope gives it access to wasmModule / __wbg_get_imports / __wbg_finalize_init.
export function __tineReinstantiate() {
  if (wasmModule === undefined) throw new Error('lsdoc-wasm: reinit before init');
  const instance = new WebAssembly.Instance(wasmModule, __wbg_get_imports());
  return __wbg_finalize_init(instance, wasmModule);
}
`,
);
writeFileSync(join(outDir, "lsdoc_wasm.js"), glue);

let dts = readFileSync(join(tmp, "lsdoc_wasm.d.ts"), "utf8");
const dtsAnchor = "export function render_block_html(raw: string, is_org: boolean): string;\n";
if (!dts.includes(dtsAnchor)) {
  throw new Error(
    "build-wasm: expected render_block_html declaration not found in .d.ts — wasm-bindgen output " +
      "changed; re-check the Tine crash-recovery type injection in scripts/build-wasm.mjs.",
  );
}
if (dts.includes("__tineReinstantiate")) {
  throw new Error("build-wasm: __tineReinstantiate already present in generated .d.ts; refuse to duplicate it.");
}
dts = dts.replace(dtsAnchor, `${dtsAnchor}\nexport function __tineReinstantiate(): void;\n`);
writeFileSync(join(outDir, "lsdoc_wasm.d.ts"), dts);

console.log(
  `vendored → src/render/wasm/ (lsdoc_wasm.js, lsdoc_wasm.d.ts, lsdoc_wasm_bytes.ts; ` +
    `${(wasm.length / 1024).toFixed(0)} KB wasm → ${(b64.length / 1024).toFixed(0)} KB base64)`,
);
