#!/usr/bin/env node
// Regenerate the vendored frontend parser (src/render/wasm/) from crates/lsdoc-wasm.
//
// Run via `npm run build:wasm`. Needs `wasm-pack` + the `wasm32-unknown-unknown`
// target (NOT needed to merely build/run Tine — only to regenerate after an lsdoc
// bump). See docs/wasm-parse-plan.md.
//
// Steps:
//   1. Read the lsdoc git tag from crates/tine-core/Cargo.toml (the single source
//      of truth) and from crates/lsdoc-wasm/Cargo.toml; REFUSE if they differ
//      (the stale-wasm / forgot-to-bump guard, plan §7D).
//   2. wasm-pack build --target web (release), LSDOC_TAG stamped in.
//   3. Base64-encode the .wasm into src/render/wasm/lsdoc_wasm_bytes.ts and copy
//      the wasm-bindgen JS glue + .d.ts. These committed files are what the app
//      and CI consume — no fetch, no wasm toolchain at app-build time.

import { execFileSync } from "node:child_process";
import { readFileSync, writeFileSync, mkdtempSync, mkdirSync } from "node:fs";
import { homedir, tmpdir } from "node:os";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const outDir = join(root, "src", "render", "wasm");

function lsdocTag(cargoTomlRelPath) {
  const txt = readFileSync(join(root, cargoTomlRelPath), "utf8");
  const m = txt.match(/lsdoc\s*=\s*\{[^}]*\btag\s*=\s*"([^"]+)"/);
  if (!m) throw new Error(`could not find lsdoc tag in ${cargoTomlRelPath}`);
  return m[1];
}

const coreTag = lsdocTag("crates/tine-core/Cargo.toml");
const wrapTag = lsdocTag("crates/lsdoc-wasm/Cargo.toml");
if (coreTag !== wrapTag) {
  console.error(
    `\n  lsdoc pin mismatch (plan §7D guard):\n` +
      `    crates/tine-core/Cargo.toml  -> ${coreTag}\n` +
      `    crates/lsdoc-wasm/Cargo.toml -> ${wrapTag}\n` +
      `  Bump both to the same tag before regenerating the wasm.\n`,
  );
  process.exit(1);
}
console.log(`lsdoc pin: ${coreTag} (tine-core == lsdoc-wasm ✓)`);

const tmp = mkdtempSync(join(tmpdir(), "lsdoc-wasm-"));
console.log(`wasm-pack build → ${tmp}`);
// Panic locations embed source paths. Without the remap the checkout's
// absolute path (a private worktree name) ships in the public bytes, and the
// clean-source rebuild check can never match a build made in another checkout.
// Dependency sources live under CARGO_HOME (a local toolchain dir here,
// ~/.cargo on CI); remap it too so the bytes do not depend on the machine.
const cargoHome = process.env.CARGO_HOME || join(homedir(), ".cargo");
// A toolchain with rust-src installed reports std panic locations under its
// local sysroot; map them back to the canonical /rustc/<commit> form that a
// toolchain without rust-src already uses.
const rustcCommit = execFileSync("rustc", ["-vV"], { cwd: root, encoding: "utf8" }).match(/^commit-hash: (\S+)$/m)?.[1];
const sysroot = execFileSync("rustc", ["--print", "sysroot"], { cwd: root, encoding: "utf8" }).trim();
if (!rustcCommit) throw new Error("build-wasm: rustc -vV reported no commit-hash");
const rustflags = [
  process.env.RUSTFLAGS,
  `--remap-path-prefix=${root}=/tine`,
  `--remap-path-prefix=${cargoHome}=/cargo`,
  `--remap-path-prefix=${join(sysroot, "lib", "rustlib", "src", "rust")}=/rustc/${rustcCommit}`,
].filter(Boolean).join(" ");
execFileSync(
  "wasm-pack",
  ["build", "crates/lsdoc-wasm", "--target", "web", "--release", "--out-dir", tmp, "--out-name", "lsdoc_wasm"],
  { cwd: root, stdio: "inherit", env: { ...process.env, LSDOC_TAG: coreTag, RUSTFLAGS: rustflags } },
);

mkdirSync(outDir, { recursive: true });

// 1) Base64-inline the wasm bytes (no fetch under Tauri custom-protocol).
const wasm = readFileSync(join(tmp, "lsdoc_wasm_bg.wasm"));
const b64 = wasm.toString("base64");
const bytesTs =
  `// GENERATED by scripts/build-wasm.mjs — DO NOT EDIT.\n` +
  `// lsdoc ${coreTag}; raw wasm ${wasm.length} bytes, base64 ${b64.length} chars.\n` +
  `// Base64-inlined so the parser loads with NO fetch (works under Tauri's custom\n` +
  `// protocol + offline). Regenerate via \`npm run build:wasm\`.\n` +
  `export const LSDOC_TAG = ${JSON.stringify(coreTag)};\n` +
  `export const WASM_B64 = ${JSON.stringify(b64)};\n`;
writeFileSync(join(outDir, "lsdoc_wasm_bytes.ts"), bytesTs);

// 2) Vendor the wasm-bindgen JS glue + its type defs. Neutralize the glue's
//    default-path branch: `new URL('lsdoc_wasm_bg.wasm', import.meta.url)` would
//    make Vite statically emit/resolve the raw .wasm at build time — but we vendor
//    base64 only (no raw .wasm) and ALWAYS pass bytes to init(), so that branch is
//    dead code. Replace it so Vite never sees the asset URL.
let glue = readFileSync(join(tmp, "lsdoc_wasm.js"), "utf8");
const defaultPath = "module_or_path = new URL('lsdoc_wasm_bg.wasm', import.meta.url);";
if (!glue.includes(defaultPath)) {
  throw new Error(
    "build-wasm: expected default-path line not found in glue — wasm-bindgen output " +
      "changed; re-check the Vite asset-URL neutralization in scripts/build-wasm.mjs.",
  );
}
glue = glue.replace(
  defaultPath,
  "throw new Error('lsdoc-wasm: init() must be called with explicit bytes (see src/render/parse.ts); default fetch path is disabled.');",
);
const reinitAnchor = "export { initSync, __wbg_init as default };\n";
if (!glue.includes(reinitAnchor)) {
  throw new Error(
    "build-wasm: expected final export line not found in glue — wasm-bindgen output " +
      "changed; re-check the Tine crash-recovery reinit injection in scripts/build-wasm.mjs.",
  );
}
if (glue.includes("__tineReinstantiate")) {
  throw new Error("build-wasm: __tineReinstantiate already present in generated glue; refuse to duplicate it.");
}
glue = glue.replace(
  reinitAnchor,
  reinitAnchor +
    `
// Tine crash-recovery: rebuild a FRESH wasm instance from the retained compiled module,
// bypassing the init()/initSync() \`wasm !== undefined\` early-return. Used by
// src/render/parse.ts to recover from a parser trap (poisoned instance). Same-module
// scope gives it access to wasmModule / __wbg_get_imports / __wbg_finalize_init.
export function __tineReinstantiate() {
  if (wasmModule === undefined) throw new Error('lsdoc-wasm: reinit before init');
  const instance = new WebAssembly.Instance(wasmModule, __wbg_get_imports());
  return __wbg_finalize_init(instance, wasmModule);
}
`,
);
// Tine trap isolation (I-2): a Rust panic is an `unreachable` trap (panic = "abort"), and a
// trap leaves the instance unusable for the session (leaked shadow stack, RefCell borrows that
// never release). Only two doors used to recover (parse_block_bundle_json, header_tokens_json);
// every other door took the whole page down with the next call. Wrap EVERY export so a trap
// (or a stack overflow) reinstantiates a fresh instance and surfaces as an ordinary Error
// carrying the panic message (see `last_panic` in crates/lsdoc-wasm), never as a poisoned
// instance. The rename keeps the generated bindings byte-identical underneath.
const exported = [...glue.matchAll(/^export function (\w+)\(/gm)].map((m) => m[1]).filter((n) => n !== "__tineReinstantiate");
if (!exported.includes("last_panic")) {
  throw new Error("build-wasm: last_panic export missing from glue — crates/lsdoc-wasm lost its panic hook.");
}
for (const name of exported) glue = glue.replace(new RegExp(`^export function ${name}\\(`, "m"), `function __tine_raw_${name}(`);
glue +=
  `
// Tine trap isolation: see scripts/build-wasm.mjs. One guarded export per wasm-bindgen export.
function __tineGuard(name, raw) {
  return function (...args) {
    try {
      return raw.apply(this, args);
    } catch (e) {
      const trapped =
        (typeof WebAssembly !== 'undefined' && e instanceof WebAssembly.RuntimeError) ||
        (e instanceof RangeError && /call stack/i.test(String(e.message)));
      if (!trapped) throw e;
      let panic = '';
      try { panic = __tine_raw_last_panic(); } catch (_) { /* the instance is too far gone to answer */ }
      __tineReinstantiate();
      throw new Error('lsdoc-wasm trap in ' + name + ': ' + (panic || e.message), { cause: e });
    }
  };
}
` +
  exported.map((n) => `export const ${n} = __tineGuard(${JSON.stringify(n)}, __tine_raw_${n});\n`).join("");
writeFileSync(join(outDir, "lsdoc_wasm.js"), glue);

let dts = readFileSync(join(tmp, "lsdoc_wasm.d.ts"), "utf8");
const dtsAnchor = "export function render_block_html(raw: string, is_org: boolean): string;\n";
if (!dts.includes(dtsAnchor)) {
  throw new Error(
    "build-wasm: expected render_block_html declaration not found in .d.ts — wasm-bindgen output " +
      "changed; re-check the Tine crash-recovery type injection in scripts/build-wasm.mjs.",
  );
}
if (dts.includes("__tineReinstantiate")) {
  throw new Error("build-wasm: __tineReinstantiate already present in generated .d.ts; refuse to duplicate it.");
}
dts = dts.replace(dtsAnchor, `${dtsAnchor}\nexport function __tineReinstantiate(): void;\n`);
writeFileSync(join(outDir, "lsdoc_wasm.d.ts"), dts);

console.log(
  `vendored → src/render/wasm/ (lsdoc_wasm.js, lsdoc_wasm.d.ts, lsdoc_wasm_bytes.ts; ` +
    `${(wasm.length / 1024).toFixed(0)} KB wasm → ${(b64.length / 1024).toFixed(0)} KB base64)`,
);
