use tauri::Emitter;

const HISTORY_NAVIGATE_EVENT: &str = "history-navigate";

#[derive(Clone, serde::Serialize)]
struct HistoryNavigatePayload {
    direction: &'static str,
    target: String,
}

fn emit_navigation(window: &tauri::WebviewWindow, direction: &'static str) {
    let _ = window.emit(
        HISTORY_NAVIGATE_EVENT,
        HistoryNavigatePayload {
            direction,
            // Tauri's Emitter::emit broadcasts to every webview. Keep the
            // originating graph authoritative in the frontend listener.
            target: window.label().to_string(),
        },
    );
}

/// Route native mouse history buttons into the frontend router for one graph
/// webview. Linux and Windows need different native interception boundaries;
/// other platforms retain the DOM `auxclick` fallback.
pub(crate) fn install(window: &tauri::WebviewWindow) {
    platform::install(window);
}

#[cfg(target_os = "linux")]
mod platform {
    use super::emit_navigation;

    // Wry's WebKitGTK backend verifies the native GDK mapping and translates
    // these to DOM buttons 3/4 in synthetic_mouse_events.rs.
    const GDK_BUTTON_BACK: u32 = 8;
    const GDK_BUTTON_FORWARD: u32 = 9;

    pub(super) fn install(window: &tauri::WebviewWindow) {
        let event_window = window.clone();
        let _ = window.with_webview(move |platform_webview| {
            use gtk::{
                gdk::{EventButton, EventType, FromEvent},
                prelude::WidgetExt,
            };

            platform_webview.inner().connect_event(move |_, event| {
                if !matches!(
                    event.event_type(),
                    EventType::ButtonPress | EventType::ButtonRelease
                ) {
                    return gtk::glib::Propagation::Proceed;
                }
                let Ok(button_event) = <EventButton as FromEvent>::from(event.clone()) else {
                    return gtk::glib::Propagation::Proceed;
                };
                let direction = match button_event.button() {
                    GDK_BUTTON_BACK => "back",
                    GDK_BUTTON_FORWARD => "forward",
                    _ => return gtk::glib::Propagation::Proceed,
                };

                // GtkWidget::event runs before the more-specific
                // button-{press,release}-event signal. Stop both halves here so
                // Wry cannot also synthesize DOM input/default history; navigate
                // once, on release, to preserve normal click semantics.
                if event.event_type() == EventType::ButtonRelease {
                    emit_navigation(&event_window, direction);
                }
                gtk::glib::Propagation::Stop
            });
        });
    }
}

#[cfg(target_os = "windows")]
mod platform {
    use super::emit_navigation;
    use std::ffi::c_void;

    type Hwnd = *mut c_void;
    type SubclassProc =
        Option<unsafe extern "system" fn(Hwnd, u32, usize, isize, usize, usize) -> isize>;

    // winuser.h / commctrl.h constants. WM_APPCOMMAND is generated by
    // DefWindowProc for XBUTTON releases and bubbles from child HWNDs (the
    // WebView2 content) to this top-level Tauri window.
    const WM_NCDESTROY: u32 = 0x0082;
    const WM_APPCOMMAND: u32 = 0x0319;
    const FAPPCOMMAND_MASK: u16 = 0xf000;
    const APPCOMMAND_BROWSER_BACKWARD: u16 = 1;
    const APPCOMMAND_BROWSER_FORWARD: u16 = 2;
    const HISTORY_SUBCLASS_ID: usize = 0x5449_4e45; // "TINE"

    #[link(name = "comctl32")]
    extern "system" {
        fn SetWindowSubclass(
            hwnd: Hwnd,
            callback: SubclassProc,
            id: usize,
            reference_data: usize,
        ) -> i32;
        fn RemoveWindowSubclass(hwnd: Hwnd, callback: SubclassProc, id: usize) -> i32;
        fn DefSubclassProc(hwnd: Hwnd, message: u32, wparam: usize, lparam: isize) -> isize;
    }

    unsafe extern "system" fn history_subclass_proc(
        hwnd: Hwnd,
        message: u32,
        wparam: usize,
        lparam: isize,
        _id: usize,
        reference_data: usize,
    ) -> isize {
        let window_ptr = reference_data as *mut tauri::WebviewWindow;

        if message == WM_APPCOMMAND && !window_ptr.is_null() {
            // GET_APPCOMMAND_LPARAM: command is the high word with the device
            // bits masked off by ~FAPPCOMMAND_MASK.
            let command = ((lparam as usize >> 16) as u16) & !FAPPCOMMAND_MASK;
            let direction = match command {
                APPCOMMAND_BROWSER_BACKWARD => Some("back"),
                APPCOMMAND_BROWSER_FORWARD => Some("forward"),
                _ => None,
            };
            if let Some(direction) = direction {
                // SAFETY: reference_data owns a boxed WebviewWindow until
                // WM_NCDESTROY below; the subclass runs on its owning UI thread.
                emit_navigation(unsafe { &*window_ptr }, direction);
                return 1; // TRUE: suppress WebView2/default browser navigation.
            }
        }

        if message == WM_NCDESTROY && !window_ptr.is_null() {
            // Keep the state alive while the remaining subclass chain handles
            // destruction, then release the box exactly once.
            unsafe {
                RemoveWindowSubclass(hwnd, Some(history_subclass_proc), HISTORY_SUBCLASS_ID);
                let result = DefSubclassProc(hwnd, message, wparam, lparam);
                drop(Box::from_raw(window_ptr));
                return result;
            }
        }

        unsafe { DefSubclassProc(hwnd, message, wparam, lparam) }
    }

    pub(super) fn install(window: &tauri::WebviewWindow) {
        let Ok(hwnd) = window.hwnd() else {
            return;
        };
        let state = Box::into_raw(Box::new(window.clone()));
        // SAFETY: setup/graph creation invokes this on Tao's UI thread. The box
        // is transferred to the subclass on success and freed at WM_NCDESTROY.
        let installed = unsafe {
            SetWindowSubclass(
                hwnd.0 as Hwnd,
                Some(history_subclass_proc),
                HISTORY_SUBCLASS_ID,
                state as usize,
            )
        };
        if installed == 0 {
            // SAFETY: ownership was not transferred when installation failed.
            unsafe { drop(Box::from_raw(state)) };
        }
    }
}

#[cfg(not(any(target_os = "linux", target_os = "windows")))]
mod platform {
    pub(super) fn install(_window: &tauri::WebviewWindow) {}
}
