.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH tine-export-static 1  "static " 
.SH NAME
tine\-export\-static \- Write the static HTML site
.SH SYNOPSIS
\fBtine export static\fR [\fB\-\-output\fR] [\fB\-\-all\-pages\fR] [\fB\-\-debug\fR] [\fB\-\-replace\fR] [\fB\-h\fR|\fB\-\-help\fR] <\fIGRAPH\fR> 
.SH DESCRIPTION
Write the static HTML site
.SH OPTIONS
.TP
\fB\-\-output\fR \fI<DIRECTORY>\fR [default: publish]
Graph\-relative output directory
.TP
\fB\-\-all\-pages\fR
Publish every page, ignoring `public:: true` selection for this run
.TP
\fB\-\-debug\fR
Enable diagnostic logging for the desktop app
.TP
\fB\-\-replace\fR
Retire an existing output into recovery and install the new export
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fIGRAPH\fR>

