.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH tine-doctor 1  "doctor " 
.SH NAME
tine\-doctor \- Check that a graph can be discovered and parsed without changing it
.SH SYNOPSIS
\fBtine doctor\fR [\fB\-\-debug\fR] [\fB\-h\fR|\fB\-\-help\fR] <\fIGRAPH\fR> 
.SH DESCRIPTION
Check that a graph can be discovered and parsed without changing it
.SH OPTIONS
.TP
\fB\-\-debug\fR
Enable diagnostic logging for the desktop app
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fIGRAPH\fR>

