import { expect, it, vi } from "vitest";
vi.mock("./warmCache", () => ({ waitForWarmCache: async () => true }));
import { backend } from "./backend";
import { blockRefCount } from "./blockRefCounts";
import { installPageIndex } from "./pageIndex";
import { loadFeed, setRaw, resetStore, flushPage } from "./document";
import { dataRev, bumpGraphEpoch } from "./graphSession";
it.each([2000,10000])("ordinary save IPC on %i pages", async (pages) => {
 resetStore();
 const entries = Array.from({length:pages}, (_,i)=> ({ key: `p${i}`, name: `P${i}`, is_journal:false, day:null, target:{ kind:"existing" as const, id:`pages/P${i}.md`, others:[] } }));
 const counts = Object.fromEntries(entries.map((_,i)=>[`00000000-0000-4000-8000-${String(i).padStart(12,"0")}`,1]));
 const inventory = {rev:"1",entries};
 const names = vi.spyOn(backend(),"pageInventory").mockResolvedValue(inventory);
 const refs = vi.spyOn(backend(),"getBlockRefCounts").mockResolvedValue(counts);
 vi.spyOn(backend(),"savePages").mockResolvedValue({ok:["saved"], changes:{rev:"2", inventoryChanged:false, blockRefCounts:{}}});
 installPageIndex(); bumpGraphEpoch(); blockRefCount("body");
 await vi.waitFor(()=>expect(names.mock.calls.length).toBeGreaterThan(0));
 await vi.waitFor(()=>expect(refs.mock.calls.length).toBeGreaterThan(0));
 names.mockClear(); refs.mockClear();
 loadFeed([{id:"pages/P0.md",rev:"old",name:"P0",kind:"page",title:"P0",pre_block:null,blocks:[{id:"body",raw:"before",collapsed:false,children:[]}]}]);
 const beforeRev = dataRev();
 setRaw("body","after"); expect(await flushPage("P0")).toBe(true);
 await vi.waitFor(() => expect(dataRev()).toBeGreaterThan(beforeRev), { timeout: 1500 });
 await new Promise((resolve) => setTimeout(resolve, 0));
 console.log(JSON.stringify({pages,inventoryCalls:names.mock.calls.length,inventoryResponseBytes:Buffer.byteLength(JSON.stringify(inventory)),countCalls:refs.mock.calls.length,countResponseBytes:Buffer.byteLength(JSON.stringify(counts)), extraCalls:names.mock.calls.length + refs.mock.calls.length, extraBytes:names.mock.calls.length*Buffer.byteLength(JSON.stringify(inventory)) + refs.mock.calls.length*Buffer.byteLength(JSON.stringify(counts))}));
 const extraCalls = names.mock.calls.length + refs.mock.calls.length;
 resetStore(); vi.restoreAllMocks();
 expect(extraCalls, "I-25: text-only flushPage costs zero answer IPC; exemplar src/document/save/engine.ts").toBe(0);
});
